### ISSUE TITLE
你好，几个问题请教一下

### ISSUE THREAD

**Issue by yiiyahui** [iyu98/HowToUseiRingo#2]
感谢制作这个详细的文档。
用了好久这个项目的功能，之前是只要添加相关的重写（没有安装boxjs模块），然后飞行模式，打开地图切换tomtom后相关功能即可实现，然后再关闭飞行模式。
在ios15某个版本后天气功能失效，这是苹果的问题，后来更新ios16（线刷备份恢复）后，siri也失效了，再后来就是看到你这边的回复后，安装了boxjs后，目前siri又可用了。
所以现在的问题是
1：是不是重写和boxjs必须同时安装，试了下，不启用重写似乎是无效的。
2：刚又看了下文档，似乎地图模块和定位模块合并了，那先前的地图模块可以删除了？**同时定位模块是否要保持开启**，然后boxjs更改定位模块的导航为高德即可正常使用？
再次感谢！

**Comment by iyu98** [comment]
抱歉，回复晚了，一直没看GitHub。
1. 重写和boxjs需要同时开启。
2. 地图模块已经合并到定位了，所以安装最新的 定位模块就好了

**Comment by yiiyahui** [comment]
🥲谢谢解疑，果真是后来没装boxjs的问题。
